### ISSUE TITLE
test dir uses hard scripted values

### ISSUE THREAD

**Issue by Magissia** [freeshrugsxd/wow-addon-updater#2]
self.test_dir is set to use an hard coded value, meaning if the user isn't running Linux and does not have a user session called silvio, it will fail.

https://github.com/freeshrugsxd/wow-addon-updater/blob/master/update_wow_addons.py#L43

**Comment by freeshrugsxd** [comment]
Hey thank you! I have taken your suggestions into account and changed some things about how testing mode works in https://github.com/freeshrugsxd/wow-addon-updater/commit/c1790da5a2c302c0517877776c9ea70049d646b5. There is no need anymore to prepare a separate testing directory. A testing folder will be created automatically next to the script and random addons are installed into it every time the script is run in testing mode.

Additionally, downloaded files are now stored within %TEMP%\wow-addon-updates under Windows.

Thanks again for your feedback!
