### ISSUE TITLE
Error: can't say if local or server related

### ISSUE THREAD

**Issue by stempst0r** [freeshrugsxd/wow-addon-updater#4]
First of all: Thank you for this amazing script! Using it since a while now.
Today it didn't work anymore, I just changed some addons under [classic] and I double-checked the names of the addons.
After entering `python update_wow_addons.py` this error occurs:

```
⠲ Checking for latest versions of 11 addons. multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\stempst0r\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\stempst0r\Documents\python\wow-addon-updater\update_wow_addons.py", line 122, in find_update
    check_response_status(r)
  File "C:\Users\stempst0r\Documents\python\wow-addon-updater\update_wow_addons.py", line 288, in check_response_status
    response.raise_for_status()
  File "C:\Users\stempst0r\AppData\Roaming\Python\Python38\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://www.curseforge.com/wow/addons/deadly-boss-mods/files/all?filter-game-version=1738749986%3A67408
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\update_wow_addons.py", line 314, in <module>
    Updater(testing=False)
  File ".\update_wow_addons.py", line 103, in __init__
    self.main()
  File ".\update_wow_addons.py", line 184, in main
    arr.append(it.next(timeout=self.timeout))
  File "C:\Users\stempst0r\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 865, in next
    raise value
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://www.curseforge.com/wow/addons/deadly-boss-mods/files/all?filter-game-version=1738749986%3A67408
```

Since I'm not used to python requests I can't say if it is my fault or there is an server-sided error.

I'm running Windows 10 Pro and Python 3.8

--EDIT--
After removing the addon 'deadly-boss-mods' from the list, updating worked again... so probably an error with the source of this addon at the moment

**Comment by freeshrugsxd** [comment]
Hey,
thank you for your kind words! 

It really does look like there is something wrong on curseforge's end.
When you [follow the link](https://www.curseforge.com/wow/addons/deadly-boss-mods/files/all?filter-game-version=1738749986%3a67408) in your browser you end up on a Error 500 page.

I think you'll have to wait until they sort it out and then include DBM again.

Thank you for reaching out!

**Comment by freeshrugsxd** [comment]
Looks like its working again. 

Can you confirm that the script updates DBM successfully?

**Comment by stempst0r** [comment]
> 
> 
> Looks like its working again.
> 
> Can you confirm that the script updates DBM successfully?

Testet it some minutes ago. Same issue with classic version of DBM.  The script tries to reach [https://www.curseforge.com/wow/addons/deadly-boss-mods/files/all?filter-game-version=1738749986%3A67408](https://www.curseforge.com/wow/addons/deadly-boss-mods/files/all?filter-game-version=1738749986%3A67408) and this leads into a HTTPError 500

I'm a noob regarding to python but if I can support you in any way let me know :)

**Comment by freeshrugsxd** [comment]
That's weird. When you follow the link you posted within your browser, does it lead you to an Error page or do you see the correct page listing the classic files for DBM?

**Comment by stempst0r** [comment]
Ok, just checked it again. Now it's working without any changes in code. So definitly serversided. Thanks for your time and keep on maintaining this amazing little tool <3
